<?php

namespace Database\Seeders;


use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class Orders_ProductsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('orders_products')->insert([[
            'id' => 1,
            'order_id' => 1,
            'product_id' => 1,
            'product_name' => 'Leche',
            'quantity' => 1,
         ],
         [
            'id' => 2,
            'order_id' => 1,
            'product_id' => 2,
            'product_name' => 'Huevos',
            'quantity' => 21,
         ],
         [
            'id' => 3,
            'order_id' => 1,
            'product_id' => 37,
            'product_name' => 'Pan Bimbo',
            'quantity' => 7,
         ],
         [
            'id' => 4,
            'order_id' => 1,
            'product_id' => 3,
            'product_name' => 'Manzana Verde',
            'quantity' => 10,
         ],
         [
            'id' => 5,
            'order_id' => 1,
            'product_id' => 4,
            'product_name' => 'Pepino Cohombro',
            'quantity' => 5,
         ],
         [
            'id' => 6,
            'order_id' => 2,
            'product_id' => 5,
            'product_name' => 'Pimenton Rojo',
            'quantity' => 100,
         ],
         [
            'id' => 7,
            'order_id' => 2,
            'product_id' => 6,
            'product_name' => 'Kiwi',
            'quantity' => 60,
         ],
         [
            'id' => 8,
            'order_id' => 3,
            'product_id' => 7,
            'product_name' => 'Cebolla Cabezona Blanca Limpia',
            'quantity' => 4,
         ],
         [
            'id' => 9,
            'order_id' => 3,
            'product_id' => 8,
            'product_name' => 'Habichuela',
            'quantity' => 3,
         ],
         [
            'id' => 10,
            'order_id' => 3,
            'product_id' => 9,
            'product_name' => 'Mango Tommy Maduro',
            'quantity' => 4,
         ],
         [
            'id' => 11,
            'order_id' => 3,
            'product_id' => 10,
            'product_name' => 'Tomate Chonto',
            'quantity' => 8,
         ],
         [
            'id' => 12,
            'order_id' => 3,
            'product_id' => 11,
            'product_name' => 'Zanahoria Grande',
            'quantity' => 5,
         ],
         [
            'id' => 13,
            'order_id' => 4,
            'product_id' => 12,
            'product_name' => 'Aguacate Maduro',
            'quantity' => 3,
         ],
         [
            'id' => 14,
            'order_id' => 4,
            'product_id' => 13,
            'product_name' => 'Kale o Col Rizada',
            'quantity' => 2,
         ],
         [
            'id' => 15,
            'order_id' => 4,
            'product_id' => 14,
            'product_name' => 'Cebolla Cabezona Roja Limpia',
            'quantity' => 4,
         ],
         [
            'id' => 16,
            'order_id' => 4,
            'product_id' => 4,
            'product_name' => 'Pepino Cohombro',
            'quantity' => 2,
         ],
         [
            'id' => 17,
            'order_id' => 4,
            'product_id' => 15,
            'product_name' => 'Tomate Chonto Maduro',
            'quantity' => 3,
         ],
         [
            'id' => 18,
            'order_id' => 5,
            'product_id' => 16,
            'product_name' => 'Acelga',
            'quantity' => 1500,
         ],
         [
            'id' => 19,
            'order_id' => 6,
            'product_id' => 17,
            'product_name' => 'Espinaca Bogotana',
            'quantity' => 2,
         ],
         [
            'id' => 20,
            'order_id' => 6,
            'product_id' => 18,
            'product_name' => 'Ahuyama',
            'quantity' => 3,
         ],
         [
            'id' => 21,
            'order_id' => 6,
            'product_id' => 15,
            'product_name' => 'Tomate Chonto Maduro',
            'quantity' => 2,
         ],
         [
            'id' => 22,
            'order_id' => 6,
            'product_id' => 19,
            'product_name' => 'Cebolla Cabezona Sin Pelar',
            'quantity' => 2,
         ],
         [
            'id' => 23,
            'order_id' => 6,
            'product_id' => 20,
            'product_name' => 'Mel\u00f3n',
            'quantity' => 3,
         ],
         [
            'id' => 24,
            'order_id' => 7,
            'product_id' => 21,
            'product_name' => 'Cebolla Cabezona Roja Sin Pelar',
            'quantity' => 3,
         ],
         [
            'id' => 25,
            'order_id' => 7,
            'product_id' => 22,
            'product_name' => 'Cebolla Larga Junca',
            'quantity' => 2,
         ],
         [
            'id' => 26,
            'order_id' => 7,
            'product_id' => 23,
            'product_name' => 'Hierbabuena',
            'quantity' => 2,
         ],
         [
            'id' => 27,
            'order_id' => 7,
            'product_id' => 39,
            'product_name' => 'Lechuga Crespa Morada',
            'quantity' => 4,
         ],
         [
            'id' => 28,
            'order_id' => 7,
            'product_id' => 24,
            'product_name' => 'Lechuga Crespa Verde',
            'quantity' => 15,
         ],
         [
            'id' => 29,
            'order_id' => 8,
            'product_id' => 25,
            'product_name' => 'Lim\u00f3n Tahit\u00ed',
            'quantity' => 3,
         ],
         [
            'id' => 30,
            'order_id' => 8,
            'product_id' => 26,
            'product_name' => 'Mora de Castilla',
            'quantity' => 2,
         ],
         [
            'id' => 31,
            'order_id' => 8,
            'product_id' => 22,
            'product_name' => 'Cebolla Larga Junca',
            'quantity' => 4,
         ],
         [
            'id' => 32,
            'order_id' => 8,
            'product_id' => 27,
            'product_name' => 'Pimenton Verde',
            'quantity' => 1,
         ],
         [
            'id' => 33,
            'order_id' => 8,
            'product_id' => 5,
            'product_name' => 'Pimenton Rojo',
            'quantity' => 1,
         ],
         [
            'id' => 34,
            'order_id' => 9,
            'product_id' => 22,
            'product_name' => 'Cebolla Larga Junca',
            'quantity' => 1,
         ],
         [
            'id' => 35,
            'order_id' => 10,
            'product_id' => 7,
            'product_name' => 'Cebolla Cabezona Blanca Limpia',
            'quantity' => 1,
         ],
         [
            'id' => 36,
            'order_id' => 11,
            'product_id' => 41,
            'product_name' => 'Aguacate Pint\u00f3n',
            'quantity' => 1,
         ],
         [
            'id' => 37,
            'order_id' => 11,
            'product_id' => 19,
            'product_name' => 'Cebolla Cabezona Sin Pelar',
            'quantity' => 6,
         ],
         [
            'id' => 38,
            'order_id' => 11,
            'product_id' => 29,
            'product_name' => 'Cilantro',
            'quantity' => 1,
         ],
         [
            'id' => 39,
            'order_id' => 11,
            'product_id' => 17,
            'product_name' => 'Espinaca Bogotana',
            'quantity' => 1,
         ],
         [
            'id' => 40,
            'order_id' => 11,
            'product_id' => 30,
            'product_name' => 'Fresa jugo',
            'quantity' => 1,
         ],
         [
            'id' => 41,
            'order_id' => 12,
            'product_id' => 7,
            'product_name' => 'Cebolla Cabezona Blanca Limpia',
            'quantity' => 1,
         ],
         [
            'id' => 42,
            'order_id' => 12,
            'product_id' => 25,
            'product_name' => 'Lim\u00f3n Tahit\u00ed',
            'quantity' => 2,
         ],
         [
            'id' => 43,
            'order_id' => 12,
            'product_id' => 5,
            'product_name' => 'Pimenton Rojo',
            'quantity' => 1,
         ],
         [
            'id' => 44,
            'order_id' => 12,
            'product_id' => 31,
            'product_name' => 'Papa R-12 Madura',
            'quantity' => 25,
         ],
         [
            'id' => 45,
            'order_id' => 13,
            'product_id' => 43,
            'product_name' => 'Banano',
            'quantity' => 1,
         ],
         [
            'id' => 46,
            'order_id' => 13,
            'product_id' => 30,
            'product_name' => 'Fresa jugo',
            'quantity' => 1,
         ],
         [
            'id' => 47,
            'order_id' => 13,
            'product_id' => 32,
            'product_name' => 'Curuva',
            'quantity' => 1,
         ],
         [
            'id' => 48,
            'order_id' => 13,
            'product_id' => 33,
            'product_name' => 'Br\u00f3coli',
            'quantity' => 1,
         ],
         [
            'id' => 49,
            'order_id' => 13,
            'product_id' => 28,
            'product_name' => 'Tomate Larga Vida Maduro',
            'quantity' => 2,
         ],
         [
            'id' => 50,
            'order_id' => 14,
            'product_id' => 16,
            'product_name' => 'Acelga',
            'quantity' => 3,
         ],
         [
            'id' => 51,
            'order_id' => 14,
            'product_id' => 34,
            'product_name' => 'Aguacate Hass Pint\u00f3n',
            'quantity' => 3,
         ],
         [
            'id' => 52,
            'order_id' => 14,
            'product_id' => 35,
            'product_name' => 'Aguacate Hass Maduro',
            'quantity' => 3,
         ],
         [
            'id' => 53,
            'order_id' => 14,
            'product_id' => 12,
            'product_name' => 'Aguacate Maduro',
            'quantity' => 1,
         ],
         [
            'id' => 54,
            'order_id' => 14,
            'product_id' => 36,
            'product_name' => 'Aguacate Pint\u00f3n',
            'quantity' => 1,
         ],
         [
            'id' => 55,
            'order_id' => 15,
            'product_id' => 28,
            'product_name' => 'Tomate Larga Vida Maduro',
            'quantity' => 1,
         ]
     ]);
     }
 }
